### ISSUE TITLE
Error with Ember 2.10

### ISSUE THREAD

**Issue by medokin** [yapplabs/ember-wormhole#82]
Using latest 0.5. Looks like #74 is still broken?

DEBUG: Ember             : 2.10.0
ember.debug.js:5732DEBUG: Ember Data        : 2.10.0
ember.debug.js:5732DEBUG: jQuery            : 3.1.1
ember.debug.js:5732DEBUG: Ember Simple Auth : 1.1.0

ember-wormhole.js:39 Uncaught TypeError: Cannot read property 'createTextNode' of undefined
    at Class.init (http://localhost:4200/assets/vendor.js:151140:50)
    at Class.superWrapper [as init] (http://localhost:4200/assets/vendor.js:51395:22)
    at new Class (http://localhost:4200/assets/vendor.js:47086:17)
    at Function.create (http://localhost:4200/assets/vendor.js:47374:14)
    at CurlyComponentManager.create (http://localhost:4200/assets/vendor.js:23812:29)
    at OpenComponentOpcode.evaluate (http://localhost:4200/assets/vendor.js:58627:37)
    at VM.execute (http://localhost:4200/assets/vendor.js:65202:28)
    at Object.render (http://localhost:4200/assets/vendor.js:64776:23)
    at RootState.render (http://localhost:4200/assets/vendor.js:23099:46)
    at runInTransaction (http://localhost:4200/assets/vendor.js:34058:28)

**Comment by medokin** [comment]
Update: It works with 0.4

**Comment by lukemelia** [comment]
@medokin does https://github.com/yapplabs/ember-wormhole/issues/66#issuecomment-263575168 address your issue?

**Comment by medokin** [comment]
@lukemelia Unfortunately not.
It does not matter what the wormhole contains. It also crashes when its empty.
I will try to reproduce with an example.

**Comment by brancusi** [comment]
Getting this as well even after upgrading to 0.5.0.

```
ember-wormhole.js:39 Uncaught TypeError: Cannot read property 'createTextNode' of undefined
    at Class.init (http://localhost:5000/assets/vendor.js:117511:50)
    at Class.superWrapper [as init] (http://localhost:5000/assets/vendor.js:59746:22)
    at new Class (http://localhost:5000/assets/vendor.js:55437:17)
    at Function.create (http://localhost:5000/assets/vendor.js:55725:14)
    at CurlyComponentManager.create (http://localhost:5000/assets/vendor.js:32163:29)
    at OpenComponentOpcode.evaluate (http://localhost:5000/assets/vendor.js:66978:37)
    at VM.execute (http://localhost:5000/assets/vendor.js:73553:28)
    at VM.resume (http://localhost:5000/assets/vendor.js:73532:25)
    at TryOpcode.handleException (http://localhost:5000/assets/vendor.js:74043:29)
    at UpdatingVMFrame.handleException (http://localhost:5000/assets/vendor.js:74223:35)
```

Every use has a single root element with no siblings as described in #66 

Thanks

**Comment by brancusi** [comment]
Just noticed the fix switch `_doc.document.createTextNode` to `_doc.createTextNode` wasn't part of the 0.5.0 release. Pulling straight from git worked for me. All seems good now.

Thanks

**Comment by sly7-7** [comment]
I've encountered this as well, 0.5.0 has the buggy behavior with glimmer2, but 0.5.1 is OK with the workaround. 
Maybe this could be closed as the underlying issue is already tracked.

**Comment by medokin** [comment]
There is a 0.5.1? have not seen it on releases page...

**Comment by lukemelia** [comment]
Looks like 0.5.1 didn't get tagged or changelog'd. I'll fix shortly.

**Comment by lukemelia** [comment]
FYI: https://github.com/yapplabs/ember-wormhole/releases/tag/0.5.1
